services:
  frontend:
    build:
      context: .
      target: runner
    ports:
      - "3000:3000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/runtime-config.js"]
      interval: 10s
      timeout: 5s
      retries: 6

  tooling:
    build:
      context: .
      target: builder
    env_file:
      - .env

  storybook:
    profiles:
      - storybook
    build:
      context: .
      target: deps
    command: npm run storybook
    env_file:
      - .env
    ports:
      - "6006:6006"
    volumes:
      - .:/app
      - /app/node_modules
